### ISSUE TITLE
Strapi 3.5.3 Error

### ISSUE THREAD

**Issue by tabaktoni** [alessandrocaprarelli/strapi-provider-email-mailtrap#5]
Installed using  npm install strapi-provider-email-mailtrap --save
Configured
When start, App drop error in console:
```
[2021-03-17T19:40:48.385Z] error Bootstrap function in plugin "email" failed
[2021-03-17T19:40:48.387Z] error Error: The provider package isn't installed. Please run `npm install strapi-provider-email-mailtrap` --save
    at createProvider (C:\www\rescuApp\strapiRescue\node_modules\strapi-plugin-email\config\functions\bootstrap.js:11:11)
    at module.exports (C:\www\rescuApp\strapiRescue\node_modules\strapi-plugin-email\config\functions\bootstrap.js:20:35)
    at execBootstrap (C:\www\rescuApp\strapiRescue\node_modules\strapi\lib\Strapi.js:421:14)
    at C:\www\rescuApp\strapiRescue\node_modules\strapi\lib\Strapi.js:426:14
    at Array.map (<anonymous>)
    at Strapi.runBootstrapFunctions (C:\www\rescuApp\strapiRescue\node_modules\strapi\lib\Strapi.js:425:55)
    at Strapi.load (C:\www\rescuApp\strapiRescue\node_modules\strapi\lib\Strapi.js:364:16)
    at async Strapi.start (C:\www\rescuApp\strapiRescue\node_modules\strapi\lib\Strapi.js:191:9)
```
But package is installed !?

**Comment by alcaprar** [comment]
Can you please paste the content of the `package.json` of your project?
